<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTagAndAuthor($tag, $author, $page, $perPage)
    {
        $qb = $this->createQueryBuilder('article');

        if ($tag !== '') {
            $qb->join('article.tags', 'tag')
                ->where('tag.slug = :tag')
                ->setParameter(':tag', $tag);
        }

        if ($author !== '') {
            $qb->join('article.author', 'author')
                ->where('author.slug = :author')
                ->setParameter(':author', $author);
        }

        $perPage = intval($perPage) > 1 ? intval($perPage) : 10;

        if (intval($page) > 1) {
            $qb->setFirstResult((intval($page) - 1) * $perPage);
        }

        $qb->setMaxResults($perPage);

        $articles = $qb->getQuery()->getResult();

        return $articles;
    }
}
